######################################################################
# Automatically generated by qmake (3.1) Fri Mar 31 11:00:12 2017
######################################################################

TEMPLATE = app
TARGET = qt-hello-world
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets
