######################################################################
# Automatically generated by qmake (3.1) Fri Mar 31 11:00:12 2017
######################################################################

CONFIG += c++14
TEMPLATE = app
TARGET = qt-hello-world
INCLUDEPATH += .
QT += widgets
QT += quick

# Input
HEADERS += ClearButton.h
HEADERS += debug.h

SOURCES += main.cpp
SOURCES += debug.cpp

RESOURCES += main.qrc
